instagram/app_instagram/urls.py
from django.urls import path
from . import views

app_name = "app_instagram"

urlpatterns = [
    path("", views.main, name="main"),
    path("upload/", views.upload, name="upload"),
    path("pictures/", views.pictures, name="pictures"),
    path("pictures/remove/<int:pic_id>", views.remove_picture, name="remove"),
    path("pictures/edit/<int:pic_id>", views.edit_picture, name="edit")
]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_instagram.urls")),
    path('users/', include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='users/login.html',
        authentication_form=LoginForm),
        name="login"
         ),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

instagram/app_instagram/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


def update_filename(instance, filename):
    upload_to = "uploads"
    ext = filename.split(".")[-1]
    filename = f"{uuid4().hex}.{ext}"
    return os.path.join(upload_to, filename)


class Picture(models.Model):
    description = models.CharField(max_length=350)
    path = models.ImageField(upload_to=update_filename)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.user}: {self.path}"

instagram/users/models.py
from django.db import models

# Create your models here.

instagram/app_instagram/forms.py
from django.forms import ModelForm, CharField, ImageField, TextInput, FileInput

from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=350, widget=TextInput(attrs={"class": "form-control"}))
    path = ImageField(widget=FileInput(attrs={"class": "form-control"}))

    class Meta:
        model = Picture
        fields = ["description", "path"]

instagram/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "First Name"}))

    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Last Name"}))

    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))

    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email"}))

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control", "placeholder": "Confirm password"}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))

    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))

    class Meta:
        model = User
        fields = ['username', 'password']

instagram/app_instagram/views.py
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import PictureForm
from .models import Picture


# Create your views here.

def main(request):
    return render(request, "app_instagram/index.html", context={"title": "My Instagram"})


def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == 'POST':
        form = PictureForm(
            request.POST,
            request.FILES,
            instance=Picture()
        )
        if form.is_valid():
            form.save()
            return redirect(to="app_instagram:main")
    return render(request, "app_instagram/upload.html", context={"title": "My Instagram", "form": form})


def pictures(request):
    pictures = Picture.objects.all()
    return render(request, "app_instagram/pictures.html", context={"title": "My Instagram", "pictures": pictures})


def remove_picture(request, pic_id):
    pic = Picture.objects.filter(pk=pic_id, user=request.user) # , user=request.user
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(pic.first().path)))
    except OSError as e:
        print(e)
    pic.delete()
    return redirect(to="app_instagram:pictures")


def edit_picture(request, pic_id):
    if request.method == "POST":
        description = request.POST["description"]
        Picture.objects.filter(pk=pic_id, user=request.user).update(description=description)
        return redirect(to="app_instagram:pictures")

    picture = Picture.objects.filter(pk=pic_id, user=request.user).first()
    ctx = {"title": "My Instagram", "picture": picture}
    return render(request, "app_instagram/edit.html", context=ctx)

instagram/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy

from .forms import RegisterForm


# Create your views here.


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_instagram:main")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Ваш акаунт успішно створено: {username}')
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

    # AsdZxc@1

instagram/app_instagram/templates/app_instagram/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:pictures' %}">Pictures</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:upload' %}">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Create account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

instagram/app_instagram/templates/app_instagram/edit.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Edit picture: "{{picture.description}}"</h1>
<form action="{% url 'app_instagram:edit' picture.id %}" method="post">
  {% csrf_token %}
  <img src="/media/{{picture.path}}" style="width: 450px !important" class="card-img-top" alt="...">
  <div class="mb-3">
    <label class="form-label">Опис файлу</label>
    <input type="text" class="form-control" value="{{picture.description}}" name="description">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

instagram/app_instagram/templates/app_instagram/index.html
{% extends 'app_instagram/base.html' %}

{% block content %}
<h1>My Instagram</h1>
{% endblock %}

instagram/app_instagram/templates/app_instagram/pictures.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Your pictures</h1>
<div class="row">
    {% for picture in pictures %}
    <div class="col-md-4">
        <div class="card col-md-4" style="width: 18rem;">
            <img src="/media/{{picture.path}}" class="card-img-top" alt="...">
            <div class="card-body">
<!--                <h5 class="card-title">{{picture.path}}</h5>-->
                <p class="card-text">
                    {{picture.description}}
                </p>
                <a href="{% url 'app_instagram:edit' picture.id %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'app_instagram:remove' picture.id %}" class="btn btn-danger">Delete</a>

            </div>
        </div>

    </div>

    {% endfor %}
</div>
{% endblock %}

instagram/app_instagram/templates/app_instagram/upload.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Upload file</h1>
<form action="{% url 'app_instagram:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Опис файлу</label>
    {{ form.description }}
  </div>
  <div class="mb-3">
    <label class="form-label">Файл</label>
    {{ form.path }}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

instagram/users/templates/users/login.html
{% extends "app_instagram/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
  <span>{{ form.non_field_errors }}</span>
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{form.errors.first_name}}</span>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
        <span>{{form.errors.first_name}}</span>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
        <div class="small text-center">
            <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
    </div>
</form>
{% endblock %}

instagram/users/templates/users/logout.html
{% extends "app_instagram/base.html" %}

{% block content %}

<h1>Thank you!</h1>

{% endblock %}

instagram/users/templates/users/password_reset.html
{% extends "app_instagram/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

instagram/users/templates/users/password_reset_complete.html
{% extends "app_instagram/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

instagram/users/templates/users/password_reset_confirm.html
{% extends "app_instagram/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

instagram/users/templates/users/password_reset_done.html
{% extends "app_instagram/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

instagram/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

instagram/users/templates/users/register.html
{% extends "app_instagram/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>First Name</label>
                            {{ form.first_name }}
                        </div>
                        <span>{{form.errors.first_name}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Last Name</label>
                            {{ form.last_name }}
                        </div>
                        <span>{{form.errors.last_name}}</span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Username</label>
                            {{ form.username }}
                        </div>
                        <span>{{form.errors.username}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Email</label>
                            {{ form.email }}
                        </div>
                        <span>{{form.errors.email}}</span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Password</label>
                            {{ form.password1 }}
                        </div>
                        <span>{{form.errors.password1}}</span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Confirm password</label>
                            {{ form.password2 }}
                        </div>
                        <span>{{form.errors.password2}}</span>
                    </div>
                </div>
                <div class="form-group mt-4 mb-1">
                    <button type="submit" class="btn btn-success">Sign UP</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}